//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenFlow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenFlow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _1466070757_My_Computer {
            get {
                object obj = ResourceManager.GetObject("_1466070757_My_Computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip,latitude,longitude
        ///210,43.005895,-71.013202
        ///211,43.005895,-71.013202
        ///212,43.005895,-71.013202
        ///213,43.005895,-71.013202
        ///214,43.005895,-71.013202
        ///215,43.005895,-71.013202
        ///501,40.922326,-72.637078
        ///544,40.922326,-72.637078
        ///601,18.180103,-66.74947
        ///602,18.363285,-67.18024
        ///603,18.448619,-67.13422
        ///604,18.498987,-67.13699
        ///605,18.465162,-67.141486
        ///606,18.182151,-66.9588
        ///607,18.256995,-66.104657
        ///609,18.142002,-66.273278
        ///610,18.288319,-67.13604
        ///611,18.279531,-66.80217
        ///612,18.449732,-66.69879
        ///613 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string completezip {
            get {
                return ResourceManager.GetString("completezip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP,LAT,LNG
        ///00601,18.180555, -66.749961
        ///00602,18.361945, -67.175597
        ///00603,18.455183, -67.119887
        ///00606,18.158345, -66.932911
        ///00610,18.295366, -67.125135
        ///00612,18.402253, -66.711397
        ///00616,18.420412, -66.671979
        ///00617,18.445147, -66.559696
        ///00622,17.991245, -67.153993
        ///00623,18.083361, -67.153897
        ///00624,18.064919, -66.716683
        ///00627,18.412600, -66.863926
        ///00631,18.190607, -66.832041
        ///00637,18.076713, -66.947389
        ///00638,18.295913, -66.515588
        ///00641,18.263085, -66.712985
        ///00646,18.433150, -66.285875
        ///00647, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string coords {
            get {
                return ResourceManager.GetString("coords", resourceCulture);
            }
        }
    }
}
